### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by apearson** [apearson/node-red-contrib-insteon#7]
- [x] PLM Config Node
    - [x] Created
    - [x] Linked Up
    - [x] Working
- [x] PLM Node
    - [x] Created
    - [x] Linked Up
    - [x] Working
- [x] Device Config Node
    - [x] Created
    - [x] Linked Up
    - [x] Working
- [x] Device In node
    - [x] Created
    - [x] Linked Up
    - [x] Working
- [ ] Device Out node
    - [x] Created
    - [x] Linked Up
    - [ ] Working
- [x] Scene config node
    - [x] Created
    - [x] Linked Up
    - [x] Working
- [x] Scene In node (Not needed)
    - [x] Created
    - [x] Linked Up
    - [ ] Working
- [x] Scene Out node
    - [x] Created
    - [x] Linked Up
    - [x] Working

**Comment by apearson** [comment]
Scene In node might not be needed as there is no way for the PLM to active a scene without node-red telling the plm to

**Comment by apearson** [comment]
Device Database 
- Need to display device database in device config node

**Comment by apearson** [comment]
Device type should be a config option with a query to auto fill

**Comment by apearson** [comment]
> Device type should be a config option with a query to auto fill

This is done

**Comment by apearson** [comment]
Going to open issues instead of a long running issue
